spring.application.name=nbp-currency-converter

spring.datasource.url=jdbc:postgresql://localhost:5432/currency_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true